import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";


const ceraPro = localFont({
  src: [
    {
      path: "../public/fonts/CeraPro.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/CeraProMedium.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/CeraProBold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-cera-pro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${ceraPro.variable} font-sans`}>
        {/* use toaster in app */}
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "4rem" }}
          toastOptions={{
            success: {
              style: {
                background: "#10B981",
                color: "#fff",
              },
              duration: 3000,
            },
            error: {
              style: {
                background: "#EF4444",
                color: "#fff",
              },
              duration: 5000,
            },
          }}
        />
        {children}
        </body>
    </html>
  );
}
