import "./globals.css";
import localFont from "next/font/local";

import { CabinsFormContextProvider } from "@/context/CabinsFormContext";
import Sidebar from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";
import { Toaster } from "react-hot-toast";

const ceraPro = localFont({
  src: [
    {
      path: "../public/fonts/CeraPro.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/CeraProMedium.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/CeraProBold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-cera-pro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ceraPro.variable} font-sans`}>
        {/* context provider for the cabin */}
        <CabinsFormContextProvider>
          {/* use toaster in app */}
          <Toaster
            position="top-center"
            gutter={12}
            containerStyle={{ margin: "4rem" }}
            toastOptions={{
              success: {
                style: {
                  background: "#10B981",
                  color: "#fff",
                },
                duration: 3000,
              },
              error: {
                style: {
                  background: "#EF4444",
                  color: "#fff",
                },
                duration: 5000,
              },
            }}
          />
          <div className="flex h-[100dvh]">
            <Sidebar />
            <div className="flex flex-1 flex-col ">
              <Header />
              <main className="relative h-full overflow-y-scroll bg-gray-50 pb-24 pe-16 ps-8 pt-16">
                {children}
              </main>
            </div>
          </div>
        </CabinsFormContextProvider>
      </body>
    </html>
  );
}
