import "./globals.css";
import localFont from "next/font/local";

import Sidebar from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";

const ceraPro = localFont({
  src: [
    {
      path: "../public/fonts/CeraPro.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/CeraProMedium.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/CeraProBold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-cera-pro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ceraPro.variable} font-sans`}>
        <div className="flex h-[100dvh]">
          <Sidebar />
          <div className="flex flex-1 flex-col ">
            <Header />
            <main className="h-full bg-gray-50 pb-24 pe-16 ps-8 pt-16">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
